root = "."
tmp_dir = "tmp"

[build]
    args_bin = []
    bin = "./tmp/main"
    cmd = "go build -o ./tmp/main ."
    delay = 1000
    exclude_dir = ["assets", "tmp", "vendor", "testdata"]
    exclude_file = []
    exclude_regex = ["_test.go"]
    exclude_unchanged = false
    follow_symlink = false
    full_bin = ""
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "html"]
    kill_delay = "0s"
    log = "build-errors.log"
    send_interrupt = false
    stop_on_error = true

[color]
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[log]
    time = false
    # Only show main log (silences watcher, build, runner)
    main_only = false

[misc]
    clean_on_exit = false

[screen]
    clear_on_rebuild = true
    keep_scroll = true