name: Release Charts

on:
  push:
    branches:
      - "*"

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: ${{ vars.ENV_FILE }}
    steps:
      - name: Create env file
        run: |
          touch .env
          echo $ENV_FILE >> .env
      
      - name: list of files
        run: ls -la
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fundhub-api:latest

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
