name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    # env:
    #   ENV_FILE: ${{ vars.ENV_FILE }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check go version
        run: go version

      # - name: Add env variables to .env file
      #   run: |
      #     echo $ENV_FILE >> .env

      # - name: Debug - Display Contents of .env
      #   run: cat .env

      - name: list of files
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fundhub-api:latest

  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
